---
title: "Machine learning 1 assigment"
output: html_notebook
---

Loading and diving the data

```{r}
library("mlbench")
library("caTools")
library("class")
library(mice)
library(grid)
library("rpart")



utils::data("PimaIndiansDiabetes2")
data <- PimaIndiansDiabetes2

set.seed(101) 

init = mice(data, maxit=0) 
meth = init$method
predM = init$predictorMatrix
imputed = mice(data, method=meth, predictorMatrix=predM, m=5)
data <- complete(imputed)


sample <- sample.split(data, SplitRatio = 0.8)
train <- subset(data, sample == TRUE)
test  <- subset(data, sample == FALSE)

```
KNN
```{r}
trainDf <- train[, -9]
testDf <- test[,-9]

#NA2mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
#trainDf <- replace(trainDf, TRUE, lapply(trainDf, NA2mean))
#testDf <- replace(testDf, TRUE, lapply(testDf, NA2mean))

pred.classes <- knn(trainDf, testDf, train$diabetes, k=5)
testDf <- cbind(testDf,pred.classes)

```
PCA and plot
```{r}

library(ggfortify)
autoplot(prcomp(testDf[,-9]), data = testDf, colour = 'pred.classes')
```
Error of the knn
```{r}
ks <- c(1,3,5,7,9,11,15,17,23,25,35,45,55,83,101,151 )# nearest neighbours to try
nks <- length(ks)

accuracy.train <- numeric(length=nks)
accuracy.test <- numeric(length=nks)

precision.train <- numeric(length=nks)
precision.test <- numeric(length=nks)

recall.train <- numeric(length=nks)
recall.test <- numeric(length=nks)


for (i in seq(along=ks)) {
mod.train <- knn(trainDf,trainDf,k=ks[i],cl=train$diabetes)
confussionMatrixTrain = table(mod.train, train$diabetes)
accuracy.train[i] = sum(mod.train == train$diabetes)/length(train$diabetes)
precision.train[i] = confussionMatrixTrain[1,1]/sum(confussionMatrixTrain[,1])
recall.train[i] = confussionMatrixTrain[1,1]/sum(confussionMatrixTrain[1,])

mod.test <- knn(trainDf, testDf[,-9],k= ks[i],cl= train$diabetes)
confussionMatrixTest = table(mod.test, test$diabetes)
accuracy.test[i] = sum(mod.test == test$diabetes)/length(test$diabetes)
precision.test[i] = confussionMatrixTest[1,1]/sum(confussionMatrixTest[,1])
recall.test[i] = confussionMatrixTest[1,1]/sum(confussionMatrixTest[1,])
}

#Accuracy
plot(accuracy.train,xlab="Number of NN",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Accuracy",)
axis(1, 1:length(ks), as.character(ks))
lines(accuracy.train,type="b",col='red',pch=20)
lines(accuracy.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))


#Precision
plot(precision.train,xlab="Number of NN",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Precision",)
axis(1, 1:length(ks), as.character(ks))
lines(precision.train,type="b",col='red',pch=20)
lines(precision.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))


#Recall
plot(recall.train,xlab="Number of NN",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Recall",)
axis(1, 1:length(ks), as.character(ks))
lines(recall.train,type="b",col='red',pch=20)
lines(recall.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))
```
Plotting the boundaries in different 

```{r}
col1<-c('blue', 'magenta')

plot.knn <- function(k, indexA, indexB) {
  grid.A <- seq(min(data[,indexA]), max(data[,indexA]), (max(data[,indexA]) - min(data[,indexA])) / 100)
  grid.B <- seq(min(data[,indexB]), max(data[,indexB]), (max(data[,indexB]) - min(data[,indexB])) / 100)
  grid <- expand.grid(grid.A,grid.B)
  colnames(grid) <- colnames(trainDf[, c(indexA, indexB)])
  predicted.classes <- knn(trainDf[, c(indexA, indexB)], grid, train$diabetes, k=k)
  plot(data[, indexA], data[ ,indexB], pch=20, col=col1[as.numeric(data$diabetes)], xlab=colnames(data)[indexA], ylab=colnames(data)[indexB])
  points(grid[, 1], grid[,2], pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("Classification with k=", k))
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.A), length(grid.B))
  contour(grid.A, grid.B, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.knn(5, 2, 8)
plot.knn(5, 3, 6)

```
```{r}
res.pca <- prcomp(data[,1:8], scale = TRUE)

plot.knn.pca <- function(k) {
  pca.values <- prcomp(trainDf)$x
  grid.PC1 <- seq(min(pca.values[,1]), max(pca.values[,1]), 5)
  grid.PC2 <- seq(min(pca.values[,2]), max(pca.values[,2]), 1)
  grid <- expand.grid(grid.PC1,grid.PC2)
  colnames(grid) <- c('PC1','PC2')
  predicted.classes <- knn(pca.values[,c(1,2)], grid, train$diabetes, k=k)
  plot(pca.values[,1], pca.values[,2], pch=20, col=col1[as.numeric(train$diabetes)], xlab='PC1', ylab='PC2')
  points(grid$PC1, grid$PC2, pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("PCA Classification with k=", k))
  
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.PC1), length(grid.PC2))
  contour(grid.PC1, grid.PC2, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.knn.pca(100)
plot.knn.pca(1)
```

```{r}
plot.knn.pca2 <- function(k) {
  grid.size <- 3
  grid.values <- matrix(nrow=grid.size, ncol = 8)
  for(i in seq(1:8)){
    grid.values[,i] <- seq(min(data[,i]), max(data[, i]), length.out = grid.size)
  }
  grid <- expand.grid(grid.values[,1],grid.values[,2], grid.values[,3], grid.values[,4], grid.values[,5], grid.values[,6], grid.values[,7], grid.values[,8])
  colnames(grid) <- colnames(trainDf)

  print(grid)
  predicted.classes <- knn(trainDf, grid, train$diabetes, k=k)

  
  rm<-res.pca$rotation
  ct<-res.pca$center
  sc<-res.pca$scale
  
  grid.comp1<-apply(grid,1,function(gridrow) ((gridrow-ct)/sc)%*%rm[,"PC1"])
  grid.comp2<-apply(grid,1,function(gridrow) ((gridrow-ct)/sc)%*%rm[,"PC2"])
  data.pca.comp1<-apply(data[,-9],1,function(mddrow) ((mddrow-ct)/sc)%*%rm[,"PC1"])
  data.pca.comp2<-apply(data[,-9],1,function(mddrow) ((mddrow-ct)/sc)%*%rm[,"PC2"])
  
  
  plot(data.pca.comp1, data.pca.comp2, pch=20, col=col1[as.numeric(data$diabetes)], xlab='PC1', ylab='PC2')
  points(grid.comp1,grid.comp2, pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("PCA Classification with k=", k))
  
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.comp1), length(grid.comp2))
  z <- outer(grid.comp1, grid.comp1)

  contour(grid.comp1, grid.comp2, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}

plot.knn.pca2(1)
```


Logistic regression
```{r}
glm <- glm(diabetes~.,family=binomial(logit),data=data)
summary(glm)
```
we see thath Significant are only pregnant, glucoe, intercept, mass and pedigree
```{r}
glm2 <- glm(diabetes~pregnant + glucose + insulin + mass + pedigree,family=binomial(logit),data=data)
summary(glm2)
```
now the insulin is not significant
```{r}
glm3 <- glm(diabetes~pregnant + glucose + mass + pedigree,family=binomial(logit),data=data)
summary(glm3)
```
```{r}
glm3 <- glm(diabetes~pregnant + glucose + mass + pedigree,family=binomial(logit),data=data)
summary(glm3)
```


Bundaries of logistic regression
```{r}
plot.logRegression.pca <- function() {
  pca.values <- prcomp(trainDf)$x
  pca.df <- as.data.frame.matrix(pca.values[,c(1,2)])
  pca.df$diabetes <- train$diabetes
  
  grid.PC1 <- seq(min(pca.values[,1]), max(pca.values[,1]), 5)
  grid.PC2 <- seq(min(pca.values[,2]), max(pca.values[,2]), 1)
  grid <- expand.grid(grid.PC1,grid.PC2)
  colnames(grid) <- c('PC1','PC2')
    
  glm3 <- glm(diabetes~.,family=binomial(logit),data=pca.df)
  predicted.classes <- predict(glm3, grid, type = "response")
  predicted.classes <- lapply(predicted.classes, function(x) round(x) + 1)

  plot(pca.values[,1], pca.values[,2], pch=20, col=col1[as.numeric(train$diabetes)], xlab='PC1', ylab='PC2')
  points(grid$PC1, grid$PC2, pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("PCA Classification of loggistic regression"))
  
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.PC1), length(grid.PC2))
  contour(grid.PC1, grid.PC2, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.logRegression.pca()
```
```{r}
plot.logRegression.boundaries <- function(indexA, indexB) {
  grid.A <- seq(min(data[,indexA]), max(data[,indexA]), (max(data[,indexA]) - min(data[,indexA])) / 100)
  grid.B <- seq(min(data[,indexB]), max(data[,indexB]), (max(data[,indexB]) - min(data[,indexB])) / 100)
  grid <- expand.grid(grid.A,grid.B)
  colnames(grid) <- colnames(trainDf[, c(indexA, indexB)])
  
  glm3 <- glm(diabetes~.,family=binomial(logit),data = train[, c(indexA, indexB, 9)])
  predicted.classes <- predict(glm3, grid, type = "response")
  predicted.classes <- lapply(predicted.classes, function(x) round(x) + 1)
  
  plot(data[, indexA], data[ ,indexB], pch=20, col=col1[as.numeric(data$diabetes)], xlab=colnames(data)[indexA], ylab=colnames(data)[indexB])
  
  points(grid[, 1], grid[,2], pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("Classification with logistic regression"))
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.A), length(grid.B))
  contour(grid.A, grid.B, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.logRegression.boundaries(2, 8)
plot.logRegression.boundaries(3, 6)
```

CART
```{r}
model1 <- rpart(diabetes ~., data = data, method = "class")
str(model1)
# Plot the trees
printcp(model1) # display the results
plotcp(model1) # visualize cross-validation results
summary(model1) # detailed summary of splits
predicted.classes <- predict(model1, testDf, type = "class")

print(1 - mean(predicted.classes == test$diabetes))

# plot tree
plot(model1, uniform=TRUE,
   main="Classification Tree for Diabetess")
text(model1, use.n=TRUE, all=TRUE, cex=.8)
bestcp <- model1$cptable[which.min(model1$cptable[,"xerror"]),"CP"]
model1.pruned <- prune(model1, cp = bestcp)
conf.matrix <- table(data$diabetes, predict(model1.pruned,type="class"))
rownames(conf.matrix) <- paste("Actual", rownames(conf.matrix), sep = ":")
colnames(conf.matrix) <- paste("Pred", colnames(conf.matrix), sep = ":")
print(conf.matrix)
```
```{r}
possible_bucket_sizes <- seq(1, 300, 10)
nks <- length(possible_bucket_sizes)

accuracy.train <- numeric(length=nks)
accuracy.test <- numeric(length=nks)

precision.train <- numeric(length=nks)
precision.test <- numeric(length=nks)

recall.train <- numeric(length=nks)
recall.test <- numeric(length=nks)

for(i in seq(1:length(possible_bucket_sizes))){
  cart_model <- rpart(diabetes ~., data = train, method = "class",control = rpart.control(minbucket = possible_bucket_sizes[i]))
  predicted.classes.test <- predict(cart_model, testDf, type = "class")
  predicted.classes.train <- predict(cart_model, trainDf, type = "class")

    confussionMatrixTrain = table(predicted.classes.train, train$diabetes)
    accuracy.train[i] <- mean(predicted.classes.train == train$diabetes)
    precision.train[i] = confussionMatrixTrain[1,1]/sum(confussionMatrixTrain[,1])
    recall.train[i] = confussionMatrixTrain[1,1]/sum(confussionMatrixTrain[1,])

    confussionMatrixTest = table(predicted.classes.test, test$diabetes)
    accuracy.test[i] <- mean(predicted.classes.test == test$diabetes)
    precision.test[i] = confussionMatrixTest[1,1]/sum(confussionMatrixTest[,1])
    recall.test[i] = confussionMatrixTest[1,1]/sum(confussionMatrixTest[1,])
}

#Accuracy
plot(accuracy.train,xlab="Number of items in leafs",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Accuracy",)
axis(1, 1:length(ks), as.character(ks))
lines(accuracy.train,type="b",col='red',pch=20)
lines(accuracy.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))

#Precision
plot(precision.train,xlab="Number of items in leafs",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Precision",)
axis(1, 1:length(ks), as.character(ks))
lines(precision.train,type="b",col='red',pch=20)
lines(precision.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))


#Recall
plot(recall.train,xlab="Number of items in leafs",ylab="Test error",type="n",xaxt="n", ylim=c(0.5, 1),  main="Recall",)
axis(1, 1:length(ks), as.character(ks))
lines(recall.train,type="b",col='red',pch=20)
lines(recall.test,type="b",col='blue',pch=20)
legend("bottomright",lty=1,col=c("red","blue"),legend = c("train ", "test "))

```
```{r}
plot.treeBoundaries.pca <- function(mb) {
  pca.values <- prcomp(trainDf)$x
  pca.df <- as.data.frame.matrix(pca.values[,c(1,2)])
  pca.df$diabetes <- train$diabetes
  
  grid.PC1 <- seq(min(pca.values[,1]), max(pca.values[,1]), 5)
  grid.PC2 <- seq(min(pca.values[,2]), max(pca.values[,2]), 1)
  grid <- expand.grid(grid.PC1,grid.PC2)
  colnames(grid) <- c('PC1','PC2')
    
  cart_model <- rpart(diabetes ~., data = pca.df, method = "class",control = rpart.control(minbucket = mb))
  predicted.classes <- predict(cart_model, grid, type = "class")

  plot(pca.values[,1], pca.values[,2], pch=20, col=col1[as.numeric(train$diabetes)], xlab='PC1', ylab='PC2')
  points(grid$PC1, grid$PC2, pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("PCA Classification with mini bucket size =", mb))
  
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.PC1), length(grid.PC2))
  contour(grid.PC1, grid.PC2, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.treeBoundaries.pca(1)
plot.treeBoundaries.pca(20)
plot.treeBoundaries.pca(100)

```
```{r}
plot.treeBoundaries <- function(mb, indexA, indexB) {
  grid.A <- seq(min(data[,indexA]), max(data[,indexA]), (max(data[,indexA]) - min(data[,indexA])) / 100)
  grid.B <- seq(min(data[,indexB]), max(data[,indexB]), (max(data[,indexB]) - min(data[,indexB])) / 100)
  grid <- expand.grid(grid.A,grid.B)
  colnames(grid) <- colnames(trainDf[, c(indexA, indexB)])
  
  cart_model <- rpart(diabetes ~ . , data = train[, c(indexA, indexB, 9)], method = "class",control = rpart.control(minbucket = mb))
  predicted.classes <- predict(cart_model, grid, type = "class")
  
  plot(data[, indexA], data[ ,indexB], pch=20, col=col1[as.numeric(data$diabetes)], xlab=colnames(data)[indexA], ylab=colnames(data)[indexB])
  
  points(grid[, 1], grid[,2], pch='.', col=col1[as.numeric(predicted.classes)])  # draw grid
  legend("topleft", legend=levels(data$diabetes),fill =col1)
  title(c("Classification with minibucket size=", mb))
  predicted.matrix <- matrix(as.numeric(predicted.classes), length(grid.A), length(grid.B))
  contour(grid.A, grid.B, predicted.matrix, levels=c(1.5), drawlabels=FALSE,add=TRUE)
}


plot.treeBoundaries(5, 2, 8)
plot.treeBoundaries(5, 3, 6)
```